<a href="https://colab.research.google.com/github/Priyankshu-ui-96/Machine-Learning-Dataset-practice/blob/main/feature_scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn import preprocessing 

In [3]:
data_set = pd.read_csv("/content/drive/MyDrive/Data Analytics/housingML/Data_for_Missing_Values.csv")
data_set.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [6]:
x= data_set.iloc[: , 1:3].values
print("\noriginal data values:\n", x)


original data values:
 [[4.4e+01 7.2e+04]
 [2.7e+01 4.8e+04]
 [3.0e+01 5.4e+04]
 [3.8e+01 6.1e+04]
 [4.0e+01     nan]
 [3.5e+01 5.8e+04]
 [    nan 5.2e+04]
 [4.8e+01 7.9e+04]
 [5.0e+01 8.3e+04]
 [3.7e+01 6.7e+04]]


In [8]:
from sklearn import preprocessing
normal = preprocessing.MinMaxScaler(feature_range=(0,1))
x_after_normalization = normal.fit_transform(x)
print("\n after normalization :\n" ,x_after_normalization)


 after normalization :
 [[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.56521739        nan]
 [0.34782609 0.28571429]
 [       nan 0.11428571]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]]


In [9]:
standard = preprocessing.StandardScaler()
x_after_standardization = standard.fit_transform(x)
print("\n after standardization :\n", x_after_standardization)


 after standardization :
 [[ 0.71993143  0.71101276]
 [-1.62367514 -1.36437583]
 [-1.21009751 -0.84552869]
 [-0.10722383 -0.24020701]
 [ 0.16849459         nan]
 [-0.52080146 -0.49963059]
 [        nan -1.01847774]
 [ 1.27136827  1.31633443]
 [ 1.54708669  1.66223253]
 [-0.24508304  0.27864014]]
